formatter = "nixfmt"
inherit-placement = "front"

top-level-blank-lines = 1
top-level-blank-lines-depth = 2
top-level-blank-lines-mode = "multiline"

[args]
first = ["self", "inputs", "lib", "config", "options", "pkgs", "osConfig"]
last = ["specialArgs", "<defaulted>", "..."]

[attrs]
first = ["imports", "enable", "package"]
flatten = true
blank-lines = 1
blank-lines-mode = "multiline"

[lets]
sort = true

[inherits]
sort = true

[[overrides]]
path = "**.overrideAttrs"
attrs.first = ["pname", "version", "src"]

[[overrides]]
path = "**.fetch*"
attrs.first = ["url", "owner", "repo", "rev", "tag"]

[[overrides]]
path = "**.nixpkgs.overlays"
lists.sort = false
[[overrides]]
path = "**.nixpkgs.overlays.**"
attrs.sort = false

[[overrides]]
path = "**.systemd.services.*"
attrs.first = ["enable", "description", "wantedBy", "after", "wants"]

[[overrides]]
path = "**.home.packages"
lists.sort = true
[[overrides]]
path = "**.environment.systemPackages"
lists.sort = true
