formatter = "nixfmt"
top-level-blank-lines = 1
top-level-blank-lines-mode = "multiline"

[args]
first = ["self", "inputs", "lib", "config", "options", "pkgs", "osConfig"]
last = ["<defaulted>", "..."]

[attrs]
first = ["imports", "enable", "package"]
blank-lines = 1
blank-lines-mode = "multiline"
merge = true

[lets]
sort = true

[inherits]
first = ["self", "inputs", "lib", "config", "options", "pkgs", "osConfig"]
last = ["<defaulted>", "..."]
sort = true

[[overrides]]
path = "flake-file.inputs"
attrs.blank-lines = 1

[[overrides]]
path = "**.systemd.services.*"
attrs.first = ["enable", "description", "wantedBy", "after"]

[[overrides]]
path = "**.environment.systemPackages"
lists.sort = true

[[overrides]]
path = "**.home.packages"
lists.sort = true

[[overrides]]
path = "**.networking.firewall.allowedTCPPorts"
lists.sort = true

[[overrides]]
path = "**.networking.firewall.allowedUDPPorts"
lists.sort = true
