---
  - name: Configuring distrobox
    hosts: localhost
    connection: local 
    tasks:

    - name: Set container name variable
      ansible.builtin.set_fact:
        distrobox: "{{ ansible_facts['env']['CONTAINER_ID'] }}"

    - name: Change default shell to bash
      become: yes
      ansible.builtin.user:
        name: keenan
        shell: /bin/bash

    - name: Create the `aur_builder` user
      become: yes
      ansible.builtin.user:
        name: aur_builder
        create_home: yes
        group: wheel

    - name: Allow the `aur_builder` user to run `sudo pacman` without a password
      become: yes
      ansible.builtin.lineinfile:
        path: /etc/sudoers.d/11-install-aur_builder
        line: 'aur_builder ALL=(ALL) NOPASSWD: /usr/bin/pacman /usr/bin/pacman-key'
        create: yes
        mode: 0644
        validate: 'visudo -cf %s'

    - name: Add US locale
      community.general.locale_gen:
        name: en_US.UTF-8
        state: present

    - name: Check for Chaotic AUR
      register: chaotic_aur
      ansible.builtin.stat:
        path: /etc/pacman.d/chaotic-mirrorlist

    #- name: Set up Chaotic AUR
    #  when: not chaotic_aur.stat.exists
    #  become: yes
    #  #become_user: aur_builder
    #  ansible.builtin.shell: |
    #      pacman-key --init
    #      pacman-key --recv-key 3056513887B78AEB --keyserver keyserver.ubuntu.com
    #      pacman-key --lsign-key 3056513887B78AEB
    #      pacman -U --noconfirm 'https://cdn-mirror.chaotic.cx/chaotic-aur/chaotic-keyring.pkg.tar.zst' 'https://cdn-mirror.chaotic.cx/chaotic-aur/chaotic-mirrorlist.pkg.tar.zst'

    #- name: Add Chaotic AUR to pacman.conf
    #  become: yes
    #  ansible.builtin.blockinfile:
    #    path: /etc/pacman.conf
    #    create: yes
    #    backup: yes
    #    block: |
    #      [chaotic-aur]
    #      Include = /etc/pacman.d/chaotic-mirrorlist

    - name: Install base packages
      become: yes
      community.general.pacman:
        state: present
        name:
          - base-devel
          - micro
          - pipewire
          - pipewire-alsa
          - pipewire-jack
          - pipewire-pulse
          - reflector
          - wireplumber

    - name: Remove unneeded packages
      become: yes
      community.general.pacman:
        state: absent
        name:
          - steam
          - lutris
          - xcursor-breeze

    - name: Change Pacman reflector location
      become: yes
      ansible.builtin.replace:
        path: /etc/xdg/reflector/reflector.conf
        regexp: '(\s+)# --country France,Germany(\s+.*)?$'
        replace: '\1--country US\2'

    - name: Check reflector service status
      ansible.builtin.shell: "if ! systemctl is-enabled reflector; then echo 'disabled'; fi"
      register: reflector_enabled

    - name: Enable & start reflector service
      when: reflector_enabled != "enabled"
      become: yes
      ansible.builtin.systemd_service:
        name: reflector
        enabled: true
        state: started

    - name: Check for paru.conf
      register: paru_conf
      ansible.builtin.stat:
        path: /tmp/paru.conf

    - name: Download paru.conf
      when: not paru_conf.stat.exists
      ansible.builtin.get_url:
        url: https://raw.githubusercontent.com/Morganamilo/paru/master/paru.conf
        dest: /tmp/paru.conf

    - name: Change paru.conf options
      ansible.builtin.replace:
        path: "{{ item.path }}"
        regexp: "{{ item.regex }}"
        replace: "{{ item.replace }}"
      loop:
        - { path: '/tmp/paru.conf', regex: '#SudoLoop', replace: 'SudoLoop' }
        - { path: '/tmp/paru.conf', regex: '#CleanAfter', replace: 'CleanAfter' }

    - name: Copy paru.conf to distroboxes
      ansible.builtin.copy:
        src: /tmp/paru.conf
        dest: "{{ item.path }}/"
      loop:
        - { path: '/home/keenan/.config/distrobox/bazzite-arch-exodos/.config/paru', when: "{{ distrobox }}" is "bazzite-arch-exodos" }
        - { path: '/home/keenan/.config/distrobox/bazzite-arch-gaming/.config/paru', when: "{{ distrobox }}" is "bazzite-arch-gaming" }
        - { path: '/home/keenan/.config/distrobox/bazzite-arch-sys/.config/paru', when: "{{ distrobox }}" is "bazzite-arch-sys" }

    - name: Add atuin to .bashrc
      ansible.builtin.lineinfile:
        path: "{{ item.path }}"
        create: yes
        line: 'eval "$(atuin init bash)"'
      loop:
        - { path: '/home/keenan/.config/distrobox/bazzite-arch-exodos/.bashrc', when: "{{ distrobox }}" is "bazzite-arch-exodos" }
        - { path: '/home/keenan/.config/distrobox/bazzite-arch-gaming/.bashrc', when: "{{ distrobox }}" is "bazzite-arch-gaming" }
        - { path: '/home/keenan/.config/distrobox/bazzite-arch-sys/.bashrc', when: "{{ distrobox }}" is "bazzite-arch-sys" }
 
    - name: Change atuin config paths
      ansible.builtin.blockinfile:
        path: "{{ item.path }}"
        create: yes
        backup: yes
        block: |
          db_path = "/home/keenan/.local/share/atuin/history.db"
          key_path = "/home/keenan/.local/share/atuin/key"
      loop:
        - { path: '/home/keenan/.config/distrobox/bazzite-arch-exodos/.config/atuin/config.toml', when: "{{ distrobox }}" is "bazzite-arch-exodos" }
        - { path: '/home/keenan/.config/distrobox/bazzite-arch-gaming/.config/atuin/config.toml', when: "{{ distrobox }}" is "bazzite-arch-gaming" }
        - { path: '/home/keenan/.config/distrobox/bazzite-arch-sys/.config/atuin/config.toml', when: "{{ distrobox }}" is "bazzite-arch-sys" }

    - name: Install base AUR packages
      kewlfft.aur.aur:
        use: paru
        name:
          - atuin
          - blesh
          - yay

    - name: Install distrobox specific packages (bazzite-arch-gaming)
      when: distrobox is "bazzite-arch-gaming"
      ignore_errors: true
      kewlfft.aur.aur:
        use: paru
        name:
          - gamemode
          - gamescope
          - kdialog
          - aaru
          - jazzjackrabbit
          - jazzjackrabbit2
          - lab3d-sdl
          - openxcom-extended
          - perfectdark
          - sonicthehedgehog
          - sonicthehedgehog2
          - supermario64
          - supermarioworld
          - xash3d-fwgs-git
          - zeldalttp
          - zeldamm

    - name: Install distrobox specific packages (bazzite-arch-exodos)
      when: distrobox is "bazzite-arch-exodos"
      ignore_errors: true
      kewlfft.aur.aur:
        use: paru
        name:
          - dbgl
          - gamemode
          - kdialog
          - fluidsynth
          - gwenview
          - innoextract
          - konsole
          - okular

    - name: Install distrobox specific packages (bazzite-arch-sys)
      when: distrobox is "bazzite-arch-sys"
      ignore_errors: true
      kewlfft.aur.aur:
        use: paru
        name:
          - nccm
          - python-pipx

    - name: Install qobuz-dl from pipx
      when: distrobox is "bazzite-arch-sys"
      ignore_errors: true
      ansible.builtin.shell: |
          pipx install qobuz-dl