#!/usr/bin/env bash
# distrobox_binary
# name: bazzite-arch-gaming
if [ -z "${CONTAINER_ID}" ]; then
	exec "/run/current-system/sw/bin/distrobox-enter"  -n bazzite-arch-gaming -- /usr/bin/aaru  "$@"
elif [ -n "${CONTAINER_ID}" ] && [ "${CONTAINER_ID}" != "bazzite-arch-gaming" ]; then
	exec distrobox-host-exec /home/keenan/.local/share/distrobox/exports/bin/aaru  "$@"
else
	exec /usr/bin/aaru "$@"
fi
