#!/usr/bin/env bash
# distrobox_binary
# name: bazzite-arch-sys
if [ -z "${CONTAINER_ID}" ]; then
	exec /run/current-system/sw/bin/distrobox-enter  -n bazzite-arch-sys -- 		 /home/keenan/.config/distrobox/bazzite-arch-sys/.local/bin/qobuz-dl  "$@"
else
	exec /home/keenan/.config/distrobox/bazzite-arch-sys/.local/bin/qobuz-dl "$@"
fi
